# Generated by Django 3.1.4 on 2020-12-16 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
